//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFSServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rules
    {
        public int Id { get; set; }
        public bool IsActive { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string TriggerScript { get; set; }
        public string ProcessScript { get; set; }
        public int RuleTypeId { get; set; }
        public int WebMethodId { get; set; }
    
        public virtual RuleType RuleType { get; set; }
        public virtual WebMethod WebMethod { get; set; }
    }
}
