//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFSServices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TFSServicesDBContainer : DbContext
    {
        public TFSServicesDBContainer()
            : base("name=TFSServicesDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Rules> RulesSet { get; set; }
        public virtual DbSet<RuleType> RuleTypeSet { get; set; }
        public virtual DbSet<WebMethod> WebMethodSet { get; set; }
    }
}
