//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFSServicesDBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revisions
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string UserName { get; set; }
        public string TriggerScript { get; set; }
        public string ProcessScript { get; set; }
        public int RulesId { get; set; }
        public int Revision { get; set; }
        public string Operation { get; set; }
    
        public virtual Rules Rules { get; set; }
    }
}
