//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFSServicesDBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rules()
        {
            this.IsDeleted = false;
            this.RulesRevisions = new HashSet<Revisions>();
            this.RunHistory = new HashSet<RunHistory>();
        }
    
        public int Id { get; set; }
        public bool IsActive { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string TriggerScript { get; set; }
        public string ProcessScript { get; set; }
        public int RuleTypeId { get; set; }
        public int Revision { get; set; }
        public bool IsDeleted { get; set; }
        public int Watermark { get; set; }
        public int ScheduleTypeId { get; set; }
    
        public virtual RuleType RuleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Revisions> RulesRevisions { get; set; }
        public virtual ScheduleType ScheduleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RunHistory> RunHistory { get; set; }
    }
}
