//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFSServicesDBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunHistory
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Result { get; set; }
        public int RuleRevision { get; set; }
        public string Message { get; set; }
        public Nullable<int> RulesId { get; set; }
    
        public virtual Rules Rules { get; set; }
    }
}
