//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFSServicesDBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunHistory
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Result { get; set; }
        public int RulesId { get; set; }
        public int RuleRevision { get; set; }
        public string Message { get; set; }
    
        public virtual Rules Rules { get; set; }
    }
}
