//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFSServicesDBLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TFSServicesDBContainer : DbContext
    {
        public TFSServicesDBContainer()
            : base("name=TFSServicesDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Rules> RulesSet { get; set; }
        public virtual DbSet<RuleType> RuleTypeSet { get; set; }
        public virtual DbSet<RunHistory> RunHistorySet { get; set; }
        public virtual DbSet<Revisions> RevisionsSet { get; set; }
        public virtual DbSet<ScheduleType> ScheduleTypeSet { get; set; }
    }
}
